// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZJAWUi3Iwy6GuFoJqjOiIyo3a3S6BQvU',
    appId: '1:1042981248112:web:967996235bc05de669a8b5',
    messagingSenderId: '1042981248112',
    projectId: 'melodyapp-18f75',
    authDomain: 'melodyapp-18f75.firebaseapp.com',
    storageBucket: 'melodyapp-18f75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2-n9Lq6e_jHotcfEH8jOwbQvD3iPL38Q',
    appId: '1:1042981248112:android:44320c148e19c65469a8b5',
    messagingSenderId: '1042981248112',
    projectId: 'melodyapp-18f75',
    storageBucket: 'melodyapp-18f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJAWUi3Iwy6GuFoJqjOiIyo3a3S6BQvU',
    appId: '1:1042981248112:android:44320c148e19c65469a8b5',
    messagingSenderId: '1042981248112',
    projectId: 'melodyapp-18f75',
    storageBucket: 'melodyapp-18f75.firebasestorage.app',
    iosBundleId: 'com.melody.app.melody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJAWUi3Iwy6GuFoJqjOiIyo3a3S6BQvU',
    appId: '1:1042981248112:android:44320c148e19c65469a8b5',
    messagingSenderId: '1042981248112',
    projectId: 'melodyapp-18f75',
    storageBucket: 'melodyapp-18f75.firebasestorage.app',
    iosBundleId: 'com.melody.app.melody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZJAWUi3Iwy6GuFoJqjOiIyo3a3S6BQvU',
    appId: '1:1042981248112:web:967996235bc05de669a8b5',
    messagingSenderId: '1042981248112',
    projectId: 'melodyapp-18f75',
    authDomain: 'melodyapp-18f75.firebaseapp.com',
    storageBucket: 'melodyapp-18f75.firebasestorage.app',
  );
}
